location                         = "northeurope"
resource_group_name              = "rg-timdemotf-prod"
storage_account_name             = "timdemoftprod2025dsa"
storage_account_tier             = "Standard"
storage_account_replication_type = "GRS"
container_name                   = "appdata-prod"
environment                      = "prod"
